package com.indago.helpme.gui.dashboard.statemachine;

public enum STATES {
	DEFAULT, SHIELDED, PART_SHIELDED, UNSHIELDED, PRESSED, LOCKED, CALLCENTER, CALLCENTER_PRESSED, HELP_INCOMMING, COUNTDOWN, ACCEPTED, DECLINED, FINISHED;
}
